version: 0.2
env:
  variables:
    APP_USERNAME: "A Username"
    APP_PASSWORD: "A Password"
    NODE_ENV: "test"
    SESSION_SECRET: "a session secret"
    SESSION_DURATION: 60000
    PORT: 3000
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
      - npm install -g mocha
  build:
    commands:
      - npm test
      - npm run build
artifacts:
  files:
    - "**/*"
